### ISSUE TITLE
DEBUG is too simple, new DEBUG suggestion

### ISSUE THREAD

**Issue by fefer** [intrig-unicamp/macsad#63]
Currently, the DEBUG shows only a few messages, I’d like to suggest a new organization os DEBUG with the following different level messages:

1- INFO -> Using blue color, it would inform the number of cores, threads, tables being created/initialized and inserted and the lookup mechanism
2- DEBUG -> Using magenta color, exposes what is being executed, including: tables, messages between switch and controller, adding new table entries. Furthermore, the result of a matching (fails or success), the action being executed and the port the packet arrived.
3- ERROR -> Using red color, is for when macsad crashes
4- WARNING -> Using yellow color, is for when primitives were not executed with success
5- Broadcast/Unicast -> Using green color
 
Normally a success packet would pass through 1 and 2 messages with one message of 5. However, if we find some problem in the middle of it, 3 and 4 should be interesting to highlight the problem.

**Comment by c3m3gyanesh** [comment]
Pull request #59
